GSA/datagov-infrastructure-live

test/app/output.txt, test/app/terraform.tfvars, test/db/terraform.tfvars, test/vpc/terraform.tfvars
Added test environment with sub folders of vpc/db/app.
=> Test Environment updates

ci/catalog/terraform.tfvars, ci/inventory/terraform.tfvars
=> [ci] pickup AMI fix for catalog and inventory

iam/datagov-ckan-multi.tf, iam/files/aws_eks_creds_self_manage.json
Pull in changes from https://github.com/GSA/datagov-infrastructure-live/pull/28
Adds full access to EKS for ckan-multi developers.
=> Full eks access to datagov_ckan_multi

iam/datagov-ckan-multi.tf, iam/developers.tf, iam/users.tf, iam/versions.tf
Basically just ran `terraform 0.12upgrade`
=> Fix warnings about interpolation style

iam/users.tf
I don't believe I have permissions to remove a user. This should still add Sai though
=> Add yaditi back

iam/users.tf
https://github.com/GSA/datagov-deploy/issues/1513
Revert "Add yaditi back"
This reverts commit aefccbcd4b5620e10b3e2891b4cf3d57f28873ad.
=> Remove ydave

sandbox/catalog.tf, sandbox/dashboard.tf, sandbox/inventory-2-8.tf, sandbox/inventory.tf, sandbox/jenkins.tf, sandbox/jumpbox.tf, sandbox/main.tf, sandbox/solr.tf, sandbox/wordpress.tf
https://github.com/GSA/datagov-infrastructure-live/issues/27
=> Bump datagov-infrastructure-modules

sandbox/catalog.tf
Pick up database size change (20GB).
=> Bump modules for catalog

sandbox/inventory-2-8.tf
https://github.com/GSA/datagov-deploy/issues/1536
=> [inventory] enable redis for 2.8+

sandbox/catalog-next.tf
Fixes https://circleci.com/gh/GSA/datagov-infrastructure-live/1086 (partially).
=> [catalog] specify unique name for harvester

sandbox/catalog-next.tf, sandbox/catalog.tf, sandbox/dashboard.tf, sandbox/inventory-2-8.tf, sandbox/inventory.tf, sandbox/jenkins.tf, sandbox/jumpbox.tf, sandbox/solr.tf, sandbox/wordpress.tf
https://github.com/GSA/datagov-ckan-multi/issues/287
=> Refactor security groups for Ansible/SSH

env.sample, sandbox/catalog-next.tf, sandbox/catalog.tf, sandbox/inventory-2-8.tf, sandbox/inventory.tf, sandbox/variables.tf
https://github.com/GSA/datagov-deploy/issues/1536
=> [redis] add redis password

iam/developers.tf
Plan:
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
~ update in-place
~ resource "aws_iam_group_policy" "developers_policy" {
group  = "developers"
id     = "developers:developers_policy"
name   = "developers_policy"
~ policy = jsonencode(
~ {
~ Statement = [
~ {
~ Action   = [
"iam:DeleteRolePolicy",
"iam:RemoveRoleFromInstanceProfile",
+ "iam:DeleteInstanceProfile",
]
Effect   = "Allow"
Resource = "*"
},
]
Version   = "2012-10-17"
}
)
}
Plan: 0 to add, 1 to change, 0 to destroy.
------------------------------------------------------------------------
```
=> Add DeleteInstanceProfile

iam/developers.tf
Plan:
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
~ update in-place
~ resource "aws_iam_group_policy" "developers_policy" {
group  = "developers"
id     = "developers:developers_policy"
name   = "developers_policy"
~ policy = jsonencode(
~ {
~ Statement = [
~ {
~ Action   = [
+ "iam:DeleteRole",
+ "iam:DeleteInstanceProfile",
"iam:DeleteRolePolicy",
"iam:RemoveRoleFromInstanceProfile",
- "iam:DeleteInstanceProfile",
]
Effect   = "Allow"
Resource = "*"
},
]
Version   = "2012-10-17"
}
)
}
Plan: 0 to add, 1 to change, 0 to destroy.
------------------------------------------------------------------------
```
=> Add DeleteRole

sandbox/catalog.tf
https://github.com/GSA/datagov-deploy/issues/1858
=> [catalog] fix redirect issue

iam/users.tf
Added myself, Srinivasu_Seeram as a part of onboarding tasks
=> update users.tf by adding srinivasu_seeram

sandbox/inventory.tf
Plan to be attached from Circle-Ci
```
------------------------------------------------------------------------
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
~ update in-place
~ resource "aws_security_group" "inventory" {
arn                    = "arn:aws:ec2:us-east-1:587807691409:security-group/sg-06c7764a93fa16fcf"
description            = "Security group for inventory web instance in sandbox"
~ egress                 = [
+ {
+ cidr_blocks      = [
+ "10.0.0.0/8",
]
+ description      = ""
+ from_port        = 6379
+ ipv6_cidr_blocks = []
+ prefix_list_ids  = []
+ protocol         = "tcp"
+ security_groups  = []
+ self             = false
+ to_port          = 6379
},
]
id …
```
=> Infrastructure Modules bump

sandbox/inventory-next.tf
=> bump inventory-next module

iam/users.tf
Add dan_mayol to users.tf as part of onboarding
=> Add dan_mayol to users.tf

iam/users.tf
Related issue:
https://github.com/GSA/datagov-deploy/issues/2229
=> Feature: Add karlen.manaseryan@datopian.com for AWS sandbox access

iam/users.tf
Offboarding Dan per https://github.com/GSA/datagov-deploy/issues/2374
=> Remove Dan Mayol

sandbox/catalog-next.tf, sandbox/catalog.tf, sandbox/inventory-next.tf, sandbox/inventory.tf
Part of [this work](https://github.com/GSA/datagov-deploy/issues/570)
=> bump module version

sandbox/catalog-next.tf, sandbox/catalog.tf, sandbox/inventory-next.tf, sandbox/inventory.tf
Reverts GSA/datagov-infrastructure-live#119
=> Revert "bump module version"

sandbox/jenkins.tf
Reverts GSA/datagov-infrastructure-live#121
=> Revert "[jenkins] create new instance for saml testing"

sandbox/catalog-next.tf, sandbox/catalog.tf, sandbox/inventory-next.tf, sandbox/inventory.tf
For https://github.com/GSA/datagov-deploy/issues/570
=> update ckan modules to use https in LB

sandbox/solr.tf
solr reports space full at 20 GB.
=> increase solr ebs_size from 20 to 50 GB

sandbox/jenkins.tf
=> [jenkins] remove jenkins-saml

modules/db/rds.tf, modules/redis/main.tf, modules/s3/main.tf
Updates from snyk scan.
May require tweaks to s3 configuration, pulled from [aws docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-serversideencryptionrule.html)
=> Update various compliance changes

.github/workflows/apply.yml, .github/workflows/plan.yml
=> Work-around recent bugfix with plan diffing

.github/workflows/apply.yml, .github/workflows/plan.yml
We keep seeing "plan has changed" even though the diff looks fine. Temporarily
using auto_approve.
=> Work-around plan diffing

.github/workflows/apply.yml, main.tf
Validate https://github.com/dflook/terraform-github-actions/issues/62
- Disable auto-approve
- Include dummy null resource for testing
=> Disable auto-approve

.github/workflows/apply.yml
Getting ssh errors on apply, attempting to update to latest agent
=> Update ssh agent
