GSA/datagov-infrastructure-live

bionic/inventory/terraform.tfvars, ci/inventory/terraform.tfvars
Supports the instance_type variable and sets the default to t3.small which is
needed for memory required during CKAN install.
=> Bump inventory module

bionic/catalog/terraform.tfvars, bionic/inventory/terraform.tfvars, ci/catalog/terraform.tfvars, ci/inventory/terraform.tfvars
Default is t3.small.
Still seeing playbooks fail on CKAN instances during the pip install.
=> Bump instance type for CKAN instances

iam/developers.tf
`terraform plan` says: 
```
+ resource "aws_iam_group_policy_attachment" "developers_ec2_full" {
+ group      = "developers"
+ id         = (known after apply)
+ policy_arn = "arn:aws:iam::aws:policy/AmazonEC2FullAccess"
}
+ resource "aws_iam_group_policy_attachment" "developers_efs_full" {
+ group      = "developers"
+ id         = (known after apply)
+ policy_arn = "arn:aws:iam::aws:policy/AmazonElasticFileSystemFullAccess"
}
+ resource "aws_iam_group_policy_attachment" "developers_elb_full" {
+ group      = "developers"
+ id         = (known after apply)
+ policy_arn = "arn:aws:iam::aws:policy/AmazonEC2FullAccess"
}
+ resource "aws_iam_group_policy_attachment" "developers_rds_full" {
+ group      = "developers"
+ id         = (known after …
```
=> Add to the basic developer capabilities

ci/inventory-2-8/terraform.tfvars
- Use underscores to match how Ansible's dynamic inventory parses tags
- Specify v2 inventory group for Bionic
=> [inventory] Fix Ansible groups

iam/files/aws_iam_policy_ci_terraform.json
Terraform can create new zones, so maintaining individual zones in the IAM
policy isn't what we want.
=> [iam] allow GetHostedZone on all zones

iam/files/aws_iam_policy_ci_terraform.json
Making sure https://github.com/GSA/datagov-infrastructure-live/pull/53 can apply correctly.
=> [iam] include acm permissions for cert tagging

README.md, ci/env.sample, docs/datagov-deploy-environments.md, env.sample, sandbox/README.md, sandbox/catalog.tf, sandbox/dashboard.tf, sandbox/inventory-2-8.tf, sandbox/inventory.tf, sandbox/jenkins.tf, sandbox/jumpbox.tf, sandbox/outputs.tf, sandbox/solr.tf, sandbox/wordpress.tf
Be explicit about specifying security group to instances.
This removes an implicit dependency on `data` sources expecting security groups
to pre-exist and then failing because they haven't been created yet. You only
notice this if you `terraform destroy` everything and then re-create everything
from scratch. Making the security groups explicit helps terraform to understand
the dependencies on different modules.
=> Update security groups

sandbox/inventory.tf
This makes it easier to target only the Inventory CKAN 2.5 hosts.
=> [inventory] add v1 ansible group

sandbox/catalog-next.tf
Catalog ("classic" and "next") web instances were not assigned to the appropriate web security group.  This didn't impact "classic", but it broke "next" because the web security group was used to specify an ingress rule for the redis service.
=> Bump catalog module to pick up security group fix

.circleci/config.yml
This solves two short-term problems:
1. Our state file was written with 0.12.29, but the terraform:latest tag still
points to 0.12.28 and CI refuses to touch the state file.
2. Terraform 0.13 is in RC, and we probably don't want to jump to it
immediately. There were breaking changes from 0.11 -> 0.12 and we want to
avoid rushing into that.
The "right" fix is probably to just add docker/docker-compose so that we're
using the same terraform versions in local development and CI.
=> Temporarily pin CI to use Terraform v0.12.29

env.sample
This probably isn't the right fix, but it resolves an issue that folks run into
where the aws provider in the modules doesn't know what region to use.
I think the real issue is that we need to use the provider defined in main.tf
and "pass" it to the modules.
=> Prevent "region not set" errors

sandbox/catalog-next.tf, sandbox/main.tf
Adds catalog-next-fgdc2iso service.
=> [catalog-next] add fgdc2iso service

iam/developers.tf
Make sure IAM role and instance profile permissions are allowed. Enable STS
access to decode any error messages.
=> Add missing permissions for developers

sandbox/README.md
When setting up virtualenv, pipenv ignores .python-version set by pyenv. It ends up using system newer version of python3. We have to specify the python version in pipenv command. 
References:
https://github.com/pypa/pipenv/issues/4339
https://pipenv.pypa.io/en/latest/diagnose/#pipenv-does-not-respect-pyenvs-global-and-local-python-versions
=> add steps to install and use python 3.6.8

iam/files/aws_iam_policy_ci_terraform.json
Resolves error applying a delete user plan in CI
https://app.circleci.com/pipelines/github/GSA/datagov-infrastructure-live/344/workflows/5c895ea2-b3a4-446f-adeb-33ee6cda44bd/jobs/2134
```
Error: error removing IAM User (paul.walker@datopian.com) signing certificate: Error removing signing certificates of user paul.walker@datopian.com: AccessDenied: User: arn:aws:iam::587807691409:user/datagov-ci is not authorized to perform: iam:ListSigningCertificates on resource: user paul.walker@datopian.com
status code: 403, request id: 3e317cbb-3241-4350-868c-47db828f01ff
```
=> Resolve error deleting IAM user

sandbox/jenkins.tf
```
------------------------------------------------------------------------
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create
~ update in-place
-/+ destroy and then create replacement
-/+ resource "aws_iam_instance_profile" "jenkins" {
~ arn         = "arn:aws:iam::587807691409:instance-profile/jenkins_profile-sandbox" -> (known after apply)
~ create_date = "2020-04-16T21:21:51Z" -> (known after apply)
~ id          = "jenkins_profile-sandbox" -> (known after apply)
~ name        = "jenkins_profile-sandbox" -> "jenkins_profile-ci-sandbox" # forces replacement
path        = "/"
~ role        = "jenkins_dynamic_inventory_role-sandbox" -> …
```
=> [jenkins] create new instance for saml testing

sandbox/catalog-next.tf, sandbox/catalog.tf, sandbox/inventory-next.tf, sandbox/inventory.tf
Making sure ckan apps are good with latest changes before making LoadBalancer http->https.
=> update ckan to use latest modules

sandbox/catalog-next.tf
Set the DB to be 30GB as what is currently in use, so terraform apply wont try to reduce it to default 20GB and generate error.
=> catalog-next db 30GB

sandbox/catalog-next.tf, sandbox/catalog.tf, sandbox/dashboard.tf, sandbox/inventory-next.tf, sandbox/inventory.tf, sandbox/jenkins.tf, sandbox/jumpbox.tf, sandbox/solr.tf, sandbox/wordpress.tf
Create a second instance for saml2 testing. This addresses the duplicate error
that we ran into from
https://github.com/GSA/datagov-infrastructure-live/pull/121 and restores this
work.
This also explicitly passes the aws provider to modules to prevent a "Provider
configuration missing" error.
=> [jenkins] create a second instance for saml

modules/db/rds.tf, modules/redis/main.tf, modules/s3/main.tf
Reverts GSA/datagov-infrastructure-live#137
IAM role not enabled for encryption setup
RDS size does not support encryption at rest.
System in bad state (applying previous main action did not succeed), need to re-initialize.
=> Revert "Update various compliance changes"

README.md, modules/db/rds.tf
- Remove mentions of datagov-infrastructure-modules, they are now part of this
repository.
- Update mentions of iam, they were moved to datagov-iam.
- Replace CircleCI with GH actions.
- Update CI/CD setup secrets.
- Remove references to dynamic Ansible inventory, we've been using a static
inventory for a while.
- Include a note about reviewing the terraform plan as part of peer review.
- Add prevent_destroy to database instances to prevent an accidental destroy.
=> Update docs, prevent_destroy

.github/workflows/commit.yml, Makefile, modules/catalog/versions.tf, modules/jenkins/lb.tf, modules/web/lb.tf
pin alb module for terraform 0.12 use. See https://github.com/GSA/datagov-infrastructure-live/pull/139/checks?check_run_id=2365487562 for example failures.
Also expect jenkins to be rebuilt, as it has been tainted for re-creation.
=> pin alb module for terraform 0.12

main.tf
This is mostly to work-around and help debug [this GPG verification error](https://github.com/GSA/datagov-infrastructure-live/runs/2443514087?check_suite_focus=true#step:5:76). It's unclear what version of the null provider is being downloaded. This adds a version constraint which is best practice, but also triggers a download of a new version that passes verification 🤷 .
=> Specify version constraint for null provider

modules/web/lb.tf
Related to https://github.com/GSA/datagov-deploy/issues/2730
Lock down sandbox TLS usage.
Tested manually, site functions as normal and passes compliance tests.
=> Specify latest TLS1.2 ssl policy

modules/web/lb.tf
Reduce the number of [ciphers supported][1]. Ext supports the same ciphers as
[ELBSecurityPolicy-2016-08][2], which includes "weaker" ciphers.
[1]: https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-security-policy-table.html
[2]: https://aws.amazon.com/about-aws/whats-new/2018/06/application-load-balancer-adds-new-security-policies-including-policy-for-forward-secrecy/
=> Use strict TLS 1.2 policy for ALBs

main.tf, modules/catalog/main.tf, modules/ckan-cloud/main.tf, modules/dashboard/main.tf, modules/db/main.tf, modules/inventory/main.tf, modules/jenkins/dns.tf, modules/jenkins/main.tf, modules/jumpbox/main.tf, modules/mysql/main.tf, modules/postgresdb/main.tf, modules/redis/main.tf, modules/s3/main.tf, modules/solr/main.tf, modules/stateful/main.tf, modules/stateless/main.tf, modules/vpc/main.tf, modules/web/dns.tf, modules/web/main.tf, modules/wordpress/main.tf, ssb.tf
Follows [the Terraform guide for the V3 upgrade](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-3-upgrade).
Relates to https://github.com/GSA/datagov-deploy/issues/2032
=> Upgrade aws provider
